name: 'Upload Coverage Base Action'
description: 'Custom github action for uploading base branch coverage on pull_request close event (instead of default branch push)'
inputs:
  github-token:
    description: 'GITHUB_TOKEN secret (for authentication with Github API)'
    required: true
  coveralls-token:
    description: 'Coveralls API token'
    required: true
  base-branch:
    description: 'Base branch (defaults to pull_request.head.ref falling back to "main")'
    required: false
  lcov-path:
    description: 'Path to lcov.info file'
    default: 'coverage/lcov.info'
    required: false
  coverage-artifact-name:
    description: >
      'Name of coverage artifact (useful for multiple artifacts). NOTE: Each workflow run has it's own artifacts, so name only has to be unique compared to other artifacts in the single workflow run.'
    required: false
  upload-workflow-filename:
    description: 'Filename of workflow which uploaded coverage artifact'
    default: 'verify.yml'
    required: false
  flag-name:
    description: 'Flag name'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
  post-if: 'success()'
