name: Release

on:
  push:
    branches:
      - main
      - next
      - alpha
      - beta
      # N.x (maintenance release branches)
      - '[0-9]+.x'

concurrency:
  group: release-${{ github.ref }}

jobs:
  release:
    name: Reusable release workflow
    uses: reside-eng/workflow-templates-library/.github/workflows/release_library.yml@v1
    with:
      NODE_VERSION: 16.x
      PACKAGE_MANAGER: yarn-berry
      SLACK_NOTIFICATION_SECRET: SLACK_WEBHOOK_PLATFORM_PROD
    secrets: inherit
