name: Verify

on:
  pull_request:
    branches:
      - main
      - next
      - alpha
      - beta
      # N.x (maintenance release branches)
      - '[0-9]+.x'

concurrency:
  group: verify-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Reusable verify workflow
    uses: reside-eng/workflow-templates-library/.github/workflows/verify_library.yml@v1
    with:
      NODE_VERSION: 16.x
      PACKAGE_MANAGER: yarn-berry
      SLACK_NOTIFICATION_SECRET: SLACK_WEBHOOK_PLATFORM_PROD
    secrets: inherit
